services:
  postgres:
    image: postgres:16
    container_name: pulselake-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: pulsemart
      POSTGRES_USER: pulselake
      POSTGRES_PASSWORD: pulselake_local

    ports:
      - "55432:5432"

    volumes:
      - pulselake_postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulselake -d pulsemart"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: apache/kafka:4.1.0
    container_name: pulselake-kafka
    restart: unless-stopped

    ports:
      - "19092:19092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: >
        CONTROLLER://:29093,
        INTERNAL://:29092,
        EXTERNAL://:19092

      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://kafka:29092,
        EXTERNAL://127.0.0.1:19092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        CONTROLLER:PLAINTEXT,
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - pulselake_kafka_data:/var/lib/kafka/data

volumes:
  pulselake_postgres_data:
  pulselake_kafka_data:
